[WIP] feat: miscellaneous enhancements to the bot
freeCodeCamp/camper-gh-bot pull request #8
Opened 2017-07-21 13:04 UTC by raisedadead

2017-08-14 13:11 UTC, raisedadead commented
@BerkeleyTrue I have done some updates to the bot, and will be making more in future when I have more time at hand. 

For now, this can go in as it is. I have updated the PR OP to explain whats added for now.

Can you take a look and deploy if this is ok.

2017-08-14 19:28 UTC, BerkeleyTrue requested changes

2017-08-14 19:28 UTC, BerkeleyTrue commented on package.json
> +    "coverage": "./node_modules/.bin/babel-node ./node_modules/istanbul/lib/cli cover -- node_modules/mocha/bin/_mocha --recursive --reporter spec",
You don't need to fully qualify the path of a local module. npm will automatically create a global symbol local bin files while running scripts

2017-08-17 13:34 UTC, raisedadead commented
@BerkeleyTrue I have actually gone ahead and removed the old test and coverage configs since they aren't working right now, we already have an issue to track those, and I plan to work on them.

2017-08-18 18:20 UTC, BerkeleyTrue commented
👍

2017-08-18 18:20 UTC, BerkeleyTrue approved these changes

2017-09-17 12:09 UTC, raisedadead commented
Ping @BerkeleyTrue I guess we could merge this and deploy.

2017-09-17 14:15 UTC, merged